#               Warning Dialog Messages
# 
# The system references these messages via lines that look like "message #" 
# The text that follows these lines is read until the next occurrence of
# a "message #" line.  Lines starting with '#' are ignored completely.
# The "message #" lines may have a third token that specifies how the
# message should be oriented.  For example, "message 1 center" will center
# the text for message 1 when it is displayed.  "message 1 left" will
# left justify the text when it is displayed.  This is the default action.
#
# Copyright (c) Altia, Inc. 1991-2009
#
message 1 center
This copy is for demonstration purposes only!
There is no guarantee regarding performance or functionality!
message 2 center
Functions attached to children of groups cannot be deleted.
To delete these functions, focus into the group first.
message 10 center
These errors occurred while loading the PDD:
message 11 center
These errors occurred while saving to PDD:
#
message 12 center
WARNING!  SAVING THIS FILE WILL REMOVE SPECIAL GROUPS!!!
This file contains special group types that will be lost 
if you save.  Exit now to prevent loss of information.
Alternatively, you may save to a new file name to avoid 
destroying the special groups in the original file.
#
message 13 center
These errors occurred while validating the WMIS directives:
#
message 14 center
WARNING!  CHANGES TO CONTROL CODE WILL BE LOST!!!
An error has occurred in the Control code of this object.
This should be fixed by the person who designed the object.
You may use the Control Editor to investigate this or even
change the Control code for debugging purposes.  However, 
changes to Control code cannot be saved to the PDD.
#
message 15 center
Unexpected duplicate Instance Name property values were encountered!
#
message 16 center
Unexpected duplicate instance of an object was detected!
This may cause the editor to terminate.  Altia Technical
Support can give advice on removing the duplicate instance.
The object ID with a duplicate instance is:
#
message 17 center
IMPORTANT NOTE FOR XML EXPORT OF INSTANCE OBJECTS

The design to be exported contains one or more Instance objects.
The XML file will contain the data for these Instance objects.

This release of Altia Design does not support importing an XML
file with Instance object data.  If the exported XML file is later
chosen for XML import, Altia Design will not allow the import.
# ----- WarnMsgIdCantUndo
message 18 left
WARNING: You cannot undo this operation!
# ----- WarnMsgIdNoLinkTitle
message 19 left
No Link Defined
# ----- WarnMsgIdNoLinkText
message 20 left
You have not associated this Property with an animation or value.  You may go back and edit this Property at any time in the future.
# ----- WarnMsgIdNoLinkBtn0
message 21 left
Ok
# ----- WarnMsgIdNoLinkBtn1
message 22 left
Cancel
# ----- 
